services:
  postgres1:
    image: postgres:13
    container_name: postgres_db_1
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - postgres_network
    volumes:
      - postgres1_data:/var/lib/postgresql/data
      - ./backup_utf8.sql:/docker-entrypoint-initdb.d/backup.sql

  postgres2:
    image: postgres:13
    container_name: postgres_db_2
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - postgres_network
    volumes:
      - postgres2_data:/var/lib/postgresql/data
      - ./backup_utf8.sql:/docker-entrypoint-initdb.d/backup.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - postgres_network
    depends_on:
      - postgres1
      - postgres2
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json

networks:
  postgres_network:
    name: postgres_network # Explicitly set the network name
    driver: bridge

volumes:
  postgres1_data:
  postgres2_data:
